import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AlertProvider } from '@/contexts/Alert';
import { BackdropProvider } from '@/contexts/BackDrop';
import { LanguageProvider } from '@/i18n/provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider initialLang="ja">
      <html lang="ja">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <AlertProvider>
            <BackdropProvider>{children}</BackdropProvider>
          </AlertProvider>
        </body>
      </html>
    </LanguageProvider>
  );
}
